### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by connor557** [kxes/docktop-server#1]
Would you tell me how this new system works? I'm trying to setup my docker vdi again and I'm getting lost. My old desktop based on our old platform-client system doesn't work; I think you took down the repo.

**Comment by joshiggins** [comment]
Hi connor. This is not really vdi - each application runs in separate container. The idea being that the applications can be spread across multiple servers and merged onto one desktop, instead of having one server virtualising the whole desktop + apps. It's not finished yet. If you're interested and want to help let me know. 

In the mean time, see the [pull request](https://github.com/connor557/docker-kxdesktop/pull/1) I made on your repo :wink:
